### ISSUE TITLE
OkcJS presentation once substantial progress made

### ISSUE THREAD

**Issue by joekarl** [codeforokc/school-finder#15]
Would be pretty sweet to give an overview of the project at an OkcJS meeting once we've got some more tangible progress made. 

Maybe have a talk structured around building a single page static site and all the considerations involved (from github usage to app architecture to hosting to data acquisition to delivering the product).

Would be good press for folks to see what is being done and a good way to recruit other folks.
And not only that, would make a good technical presentation on what it takes to ship a product from beginning to end, using javascript as the primary language for not only the app but tooling as well.

**Comment by DevinClark** [comment]
:+1:

**Comment by jagthedrummer** [comment]
:+1: Great idea!

**Comment by joekarl** [comment]
Now we just have to build the thing lol.

**Comment by mkchandler** [comment]
Love this idea @joekarl :+1:
