### ISSUE TITLE
Add in UI-Router for routing between about/terms/map pages

### ISSUE THREAD

**Issue by joekarl** [codeforokc/school-finder#40]
Basically just need to pull in ui-router and move the map controller declaration code into a ui-router state. 
This will allow #27 and #28 to be completed.

**Comment by DevinClark** [comment]
Important note. UI-Router fails silently for things like a controller not being found.

**Comment by joekarl** [comment]
g2k

**Comment by DevinClark** [comment]
Ran into that a few days ago and thought I would save someone like an hour here. :smile:

**Comment by mbockus** [comment]
@joekarl @DevinClark You guys already working on adding ui-router? If not, I can get a PR in after @Mike-Loffland merges. I'm pretty new to the PR workflow, so let me know if I'm doing something special.

**Comment by joekarl** [comment]
@mbockus the ui-router stuff should be orthogonal, basically just some extra bits in setup and moving the map controller setup (shouldn't have to change the controller though).

**Comment by joekarl** [comment]
oh that wasn't what you asked lol.
I haven't touched it, I think @markwissler was looking to jump in on this but he may be looking into some of the distance calc stuff with turf. 
If you want to knock it out go for it, you shouldn't need to wait for mike's changes, we'll worry about getting things merged in with whatever code is there at the time.

**Comment by joekarl** [comment]
@mbockus don't worry about stepping on toes, that's just going to happen when we're this early into a code base.

**Comment by mbockus** [comment]
@joekarl Looks like @Mike-Loffland added in ui.router in PR#4.

**Comment by Mike-Loffland** [comment]
Yea... I had already implemented it this morning before this conversation started. I should have chimed in.

**Comment by mbockus** [comment]
@Mike-Loffland No prob! Thanks for adding it.

**Comment by joekarl** [comment]
just saw this, cool going to close this as implemented in #41 (I promise we'll get this craziness figured out lol)
