### ISSUE TITLE
running gulp test 

### ISSUE THREAD

**Issue by deewuok** [codeforokc/school-finder#44]
Ran:
git clone https://github.com/codeforokc/school-finder.git
* Installed global dependencies - `npm install -g gulp-cli`
* Installed  npm dependencies - `npm install`
 also ran:
npm i --save-dev gulp-serve

gulp test
[15:52:51] Using gulpfile ~/src/school-finder/school-finder-frontend/gulpfile.js
[15:52:51] Starting 'test'...
[15:52:51] 'test' errored after 11 ms
[15:52:51] Error in plugin 'gulp-mocha'

Message:
    Cannot find module '../../app/services/currentLocationService'

**Comment by Mike-Loffland** [comment]
It's not functional yet [#32](https://github.com/codeforokc/school-finder/pull/32)

**Comment by joekarl** [comment]
Yeah, that's a bit of a borked state, tonight I'm going to work a bit on some of this.

**Comment by deewuok** [comment]
No worries, I was trying to check out what was going on.... see you maybe
next week at OKjs

You may want to play around with the map code I built in vanilla-javascript
(pull request)... I know there are built in options in Turf...that do this
better and be more succinct. But we can add that in after we get
better/more requirements.

**Comment by deewuok** [comment]
BTW,  I can go over it with folks at OKCjs... hoping to go...

**Comment by campbeja** [comment]
I also have an error in gulp-mocha, but the error message is different.
**"Message: object is not a function"**

>computer-name:school-finder-frontend joebob$ gulp test
>[14:48:22] Using gulpfile ~/Projects/github/campbeja/school-finder/school-finder-frontend/gulpfile.js
>[14:48:22] Starting 'test'...
>[14:48:22] 'test' errored after 12 ms
>[14:48:22] TypeError in plugin 'gulp-mocha'
>Message:
>    object is not a function
>Stack:
>TypeError: object is not a function
>    at Suite.<anonymous> (/Users/joebob/Projects/github/campbeja/school-finder/school-finder-frontend/tests/geolocation/geolocation_spec.js:17:14)
>    at context.describe.context.context (/Users/joebob/Projects/github/campbeja/school-finder/school-finder-frontend/node_modules/mocha/lib/interfaces/bdd.js:74:10)
>    at Object.<anonymous> (/Users/joebob/Projects/github/campbeja/school-finder/school-finder-frontend/tests/geolocation/geolocation_spec.js:8:1)
>    at Module._compile (module.js:456:26)
>    at Object.Module._extensions..js (module.js:474:10)
>    at Module.load (module.js:356:32)
>    at Function.Module._load (module.js:312:12)
>    at Module.require (module.js:364:17)
>    at require (module.js:380:17)
>    at /Users/joebob/Projects/github/campbeja/school-finder/school-finder-frontend/node_modules/mocha/lib/mocha.js:185:27

**Comment by mkchandler** [comment]
Closing this as we are not worried about the gulp tests right now.
