### ISSUE TITLE
School Finder Frontend - Building the app instructions

### ISSUE THREAD

**Issue by campbeja** [codeforokc/school-finder#48]
>Install node/npm
>Install global dependencies - npm install -g gulp-cli
>Install npm dependencies - npm install
>Run tests - gulp test -- or -- npm test

I had to use sudo for the npm install commands. After installation, I run into issues running both `gulp test` and `npm test`. Are there any commands possibly missing from the readme?

`gulp test` stack trace:
computer-name:school-finder-frontend joebob$ gulp test

module.js:340
    throw err;
    ^
Error: Cannot find module 'gulp-serve'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/joebob/Projects/github/campbeja/school-finder/school-finder-frontend/gulpfile.js:2:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

`npm test` stack trace:
> school-finder-frontend@0.0.0 test /Users/joebob/Projects/github/campbeja/school-finder/school-finder-frontend
> karma start

sh: karma: command not found
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0

**Comment by campbeja** [comment]
This issue is similar but not identical to Issue #44

**Comment by joekarl** [comment]
Yeah, testing is borked, one of the goals for today.

**Comment by Mike-Loffland** [comment]
The Readme file is not congruent with the existing code in Master... we definitely need to update the Readme. Master is not currently functioning with Gulp.

I just cloned master into a new project in attempt to reproduce Jessica's error... But, I'm getting a different error when I attempt to run the tests:

>Error: Bootstrap's JavaScript requires jQuery
>at http://localhost:9876/base/app/scripts/bootstrap.min.js?313da686ebbe387064f2d1899c64ea562b81eb40:6

There is not internal reference to jquery in karma.conf.js (only an external reference to https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js),

**Comment by Mike-Loffland** [comment]
I added the external reference in the karma.conf.js file and all the tests passed.

**Comment by joekarl** [comment]
Nice, we'll try to get the build instructions up to date as well today.

**Comment by Mike-Loffland** [comment]
Good luck today guys... family obligations prevented me from being there today.

**Comment by joekarl** [comment]
No worries, you able to make it on monday?

**Comment by Mike-Loffland** [comment]
Yup... I'll be there Monday.

**Comment by campbeja** [comment]
I was able to run `npm test` by replacing the test command package.json with `./node_modules/karma/bin/karma start`. I do not have karma installed globally.

**Comment by Mike-Loffland** [comment]
npm list -g

I did indeed install Karma globally... good catch.

**Comment by campbeja** [comment]
I can now run `gulp test` after running `sudo npm install gulp-serve --save-dev`

>computer-name:school-finder-frontend joebob$ gulp test
>[12:08:53] Using gulpfile ~/Projects/github/campbeja/school-finder/school-finder-frontend/gulpfile.js
>[12:08:53] Starting 'test'...
>[12:08:53] 'test' errored after 12 ms
>[12:08:53] TypeError in plugin 'gulp-mocha'
>Message:
>    object is not a function
>Stack:
>TypeError: object is not a function
>    at Suite.<anonymous> (/Users/joebob/Projects/github/campbeja/school-finder/school-finder->frontend/tests/geolocation/geolocation_spec.js:17:14)
>    at context.describe.context.context (/Users/joebob/Projects/github/campbeja/school-finder/school-finder-frontend/node_modules/mocha/lib/interfaces/bdd.js:74:10)
>    at Object.<anonymous> (/Users/joebob/Projects/github/campbeja/school-finder/school-finder-frontend/tests/geolocation/geolocation_spec.js:8:1)
>    at Module._compile (module.js:456:26)
>    at Object.Module._extensions..js (module.js:474:10)
>    at Module.load (module.js:356:32)
>    at Function.Module._load (module.js:312:12)
>    at Module.require (module.js:364:17)
>    at require (module.js:380:17)
>    at /Users/joebob/Projects/github/campbeja/school-finder/school-finder-frontend/node_modules/mocha/lib/mocha.js:185:27

**Comment by campbeja** [comment]
I also ran 'npm install --global gulp'
