### ISSUE TITLE
Additional source for spatial data

### ISSUE THREAD

**Issue by jagthedrummer** [codeforokc/school-finder#5]
Some of this is more up to date than other.

http://geo.ou.edu/DataFrame.htm

**Comment by joekarl** [comment]
Another good place for data will be individual school districts (see https://sis.okcps.org/sips/OKCPS001.pgm)

**Comment by joekarl** [comment]
More good data we can use... http://www.education.com/schoolfinder/tools/

**Comment by joekarl** [comment]
Oh dang, we may not be able to use the data from the education.com api due to their lame "display requirements" http://www.education.com/webservice/documentation/?section=displayrequirements

**Comment by joekarl** [comment]
Urgg... more bad news on the education.com data (see Acceptable Use; Limitations) http://www.education.com/webservice/documentation/?section=terms
