### ISSUE TITLE
Revamp all the Readmes

### ISSUE THREAD

**Issue by Mike-Loffland** [codeforokc/school-finder#57]
Eliminate the confusion.

**Comment by mkchandler** [comment]
@Mike-Loffland What kind of changes are you thinking? Consolidating them?

**Comment by Mike-Loffland** [comment]
I suppose revamp was the wrong word... I was thinking more along the lines of going over all of them and making sure they made sense to the current state of the master branch.

**Comment by mkchandler** [comment]
Ah, ok. Makes sense :+1:
