### ISSUE TITLE
Why is $StateProvider Capitilized in  angular-ui-router.js but not capitilized in  app.js

### ISSUE THREAD

**Issue by deewuok** [codeforokc/school-finder#65]
Why is $StateProvider Capitilized in  angular-ui-router.js but not capitilized in  app.js? In the lines 2143, 2144, 3494 , Javascript is Case Sensitive?

**Comment by joekarl** [comment]
Javascript is case sensitive.
I would guess it's either a typo or just inconsistent casing across the
code base.



Sent from my iPhone

On Mar 23, 2015, at 3:16 PM, Dee Wu <notifications@github.com> wrote:

Why is $StateProvider Capitilized in angular-ui-router.js but not
capitilized in app.js? In the lines 2143, 2144, 3494 , Javascript is Case
Sensitive?

—
Reply to this email directly or view it on GitHub
<https://github.com/codeforokc/school-finder/issues/65>.

**Comment by Mike-Loffland** [comment]
It breaks if I pass $StateProvder.

The naming standard for angular is camelCase.

Now I'm curious... I'll have to poke the bear a bit.

**Comment by deewuok** [comment]
maybe the order of the Dependency Injection helps override the necessity of
the $StateProvider and $stateProvider being exactly the same.   Just
pointing it out  in case you run into issues later or want to make it more
consistent between the parts of the program for readability.
