### ISSUE TITLE
Does anybody object to using Sass (scss) for app.css?

### ISSUE THREAD

**Issue by Mike-Loffland** [codeforokc/school-finder#70]
I'd like to propose that we port app.css over to Sass before it gets too unmanageable.

**Comment by deewuok** [comment]
great idea Mike... SASS could be useful to keep this burgeoning code under
control.

**Comment by deewuok** [comment]
Great Mike, Just so I can keep up, SASS sounds great with me


Angular
SASS
Mocha
Karma


 are some that I know we are probably doing 


Can we somehow get a list of what we are currently using and not using (I know some frameworks were integrated but were deemed ‘dead’ or probably need to be taken out?)
It would be nice to get an official list of the ones we are probably trying to remove from the npm

**Comment by Mike-Loffland** [comment]
Yup... I agree.
